/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Seiya.glb 
*/

import React, { useEffect } from "react";
import * as THREE from "three";
import { useGraph, type ThreeElements } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

type SeiyaModelProps = ThreeElements["group"] & {
  showModel: boolean;
};

const audio = new Audio("/audios/1_intro.wav");

export default function SeiyaModel(props: SeiyaModelProps) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/model/Seiya.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);

  console.log(names);

  // useEffect(() => {
  //   let i = 0;
  //   let interval: number;
  //   actions[names[0]]?.play();
  //   interval = setInterval(() => {
  //     console.log(names[i]);

  //     actions[names[i]]?.stop();
  //     i++;
  //     actions[names[i]]?.play();

  //     if (i === names.length) {
  //       i = 0;
  //     }
  //   }, 3000);

  //   return () => clearInterval(interval);
  // }, [actions, names]);

  useEffect(() => {
    document.addEventListener("visibilitychange", () => {
      if (document.visibilityState === "visible") {
        audio.play();
      } else {
        audio.pause();
      }
    });

    return () => {
      document.removeEventListener("visibilitychange", () => {
        audio.pause();
      });
    };
  }, []);

  useEffect(() => {
    actions["fight_idle"]?.play();
    if (!props.showModel) return;

    setTimeout(() => {
      actions["elegant"]?.play();
      actions["fight_idle"]?.stop();

      setTimeout(() => {
        audio.play();

        actions["talk"]?.play();
        actions["elegant"]?.stop();

        setTimeout(() => {
          actions["idle"]?.play();
          actions["talk"]?.stop();
        }, 8_000);
      }, 2_000);
    }, 5_000);
  }, [actions, names, props.showModel]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="0000_seiya_0_body"
            geometry={
              (nodes["0000_seiya_0_body"] as THREE.SkinnedMesh).geometry
            }
            material={materials["seiya_0_metal_bm.pngmat"]}
            skeleton={
              (nodes["0000_seiya_0_body"] as THREE.SkinnedMesh).skeleton
            }
          />
          <skinnedMesh
            name="0001_seiya_0_body"
            geometry={
              (nodes["0001_seiya_0_body"] as THREE.SkinnedMesh).geometry
            }
            material={materials["seiya_0_Simplify_bm.pngmat"]}
            skeleton={
              (nodes["0001_seiya_0_body"] as THREE.SkinnedMesh).skeleton
            }
          />
          <skinnedMesh
            name="0003_seiya_0_face"
            geometry={
              (nodes["0003_seiya_0_face"] as THREE.SkinnedMesh).geometry
            }
            material={materials.mat_seiya_0_facemat}
            skeleton={
              (nodes["0003_seiya_0_face"] as THREE.SkinnedMesh).skeleton
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/model/Seiya.glb");
