/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/Seiya.glb 
*/

import React, { useEffect } from "react";
import * as THREE from "three";
import { useGraph, type ThreeElements } from "@react-three/fiber";
import { useGLTF, useAnimations } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export default function SeiyaModel(props: ThreeElements["group"]) {
  const group = React.useRef<THREE.Group>(null);
  const { scene, animations } = useGLTF("/Seiya.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const { actions, names } = useAnimations(animations, group);

  useEffect(() => {
    actions[names[0]]?.play();
  }, [actions, names]);

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
          <skinnedMesh
            name="0000_seiya_0_body"
            geometry={
              (nodes["0000_seiya_0_body"] as THREE.SkinnedMesh).geometry
            }
            material={materials["seiya_0_metal_bm.pngmat"]}
            skeleton={
              (nodes["0000_seiya_0_body"] as THREE.SkinnedMesh).skeleton
            }
          />
          <skinnedMesh
            name="0001_seiya_0_body"
            geometry={
              (nodes["0001_seiya_0_body"] as THREE.SkinnedMesh).geometry
            }
            material={materials["seiya_0_Simplify_bm.pngmat"]}
            skeleton={
              (nodes["0001_seiya_0_body"] as THREE.SkinnedMesh).skeleton
            }
          />
          <skinnedMesh
            name="0003_seiya_0_face"
            geometry={
              (nodes["0003_seiya_0_face"] as THREE.SkinnedMesh).geometry
            }
            material={materials.mat_seiya_0_facemat}
            skeleton={
              (nodes["0003_seiya_0_face"] as THREE.SkinnedMesh).skeleton
            }
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/Seiya.glb");
